/*******************************************************************************
 * Size: 24 px
 * Bpp: 1
 ******************************************************************************/
#ifdef __has_include
    #if __has_include("lvgl.h")
        #ifndef LV_LVGL_H_INCLUDE_SIMPLE
            #define LV_LVGL_H_INCLUDE_SIMPLE
        #endif
    #endif
#endif

#ifdef LV_LVGL_H_INCLUDE_SIMPLE
    #include "lvgl.h"
#else
    #include "../lvgl-8.3.11/lvgl.h"
#endif

#ifndef COMIC_24
#define COMIC_24 1
#endif

#if COMIC_24


/*-----------------
 *    BITMAPS
 *----------------*/
/*Store the image of the glyphs*/
static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    /* U+0020 " " */
    0x0,
    /* U+0021 "!" */
    0x24, 0xed, 0xb6, 0x3, 0x0,
    /* U+0022 "\"" */
    0xde, 0xf6,
    /* U+0027 "'" */
    0xfc,
    /* U+0028 "(" */
    0xc, 0x2, 0x0, 0xc3, 0xc, 0x30, 0xc3, 0xc,
    0x30, 0xc0, 0x80, 0x3,
    /* U+0029 ")" */
    0xc0, 0x2, 0x0, 0xc, 0x30, 0xc3, 0xc, 0x30,
    0xc3, 0xc, 0x80, 0x30,
    /* U+002A "*" */
    0x18, 0x18, 0xff, 0x7c, 0x7c, 0x64, 0x64,
    /* U+002B "+" */
    0x18, 0x18, 0x18, 0xff, 0x18, 0x18, 0x18, 0x18,
    /* U+002C "," */
    0x24, 0xe0,
    /* U+002D "-" */
    0xf8,
    /* U+002E "." */
    0xc0,
    /* U+002F "/" */
    0xc, 0x30, 0xc3, 0xc, 0x82, 0x8, 0x20, 0x8c,
    0x30, 0xc3, 0xc, 0x0,
    /* U+0030 "0" */
    0x1c, 0x0, 0x23, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3,
    0xc3, 0x0, 0x3c,
    /* U+0031 "1" */
    0x33, 0xf3, 0x33, 0x33, 0x33, 0x30,
    /* U+0032 "2" */
    0x3c, 0xc3, 0x3, 0x3, 0x0, 0x4, 0x18, 0x20,
    0x20, 0x20, 0xff,
    /* U+0033 "3" */
    0x3c, 0x3, 0x3, 0x3, 0x0, 0x1c, 0x3, 0x3,
    0xc3, 0x0, 0x3c,
    /* U+0034 "4" */
    0x23, 0xc3, 0xc3, 0xc3, 0x0, 0x3c, 0xc, 0xc,
    0xc, 0xc, 0xc,
    /* U+0035 "5" */
    0x3f, 0x20, 0x20, 0xc0, 0xc0, 0xfe, 0x1, 0x1,
    0x1, 0x0, 0x3e,
    /* U+0036 "6" */
    0x1c, 0x0, 0x20, 0xc0, 0xc0, 0xfc, 0xc3, 0xc3,
    0xc3, 0x0, 0x3c,
    /* U+0037 "7" */
    0xff, 0x1, 0x1, 0x6, 0x0, 0x8, 0x30, 0x30,
    0x30, 0x30, 0x30,
    /* U+0038 "8" */
    0x1c, 0x23, 0x23, 0x23, 0x20, 0x3c, 0xc3, 0xc3,
    0xc3, 0x0, 0x3c,
    /* U+0039 "9" */
    0x3c, 0xc3, 0xc3, 0xc3, 0x3, 0x3f, 0xc, 0xc,
    0xc, 0xc, 0xc,
    /* U+003A ":" */
    0xc0, 0xc0,
    /* U+003B ";" */
    0x20, 0x12, 0x70,
    /* U+003D "=" */
    0xfc, 0x0, 0x3f,
    /* U+003F "?" */
    0xf8, 0x10, 0x41, 0x0, 0xec, 0x0, 0x0, 0xc,
    0x0,
    /* U+0041 "A" */
    0x7, 0xc, 0x46, 0x23, 0x12, 0x9, 0x4, 0xfe,
    0x81, 0xc0, 0xe0, 0x70, 0x20,
    /* U+0042 "B" */
    0x3f, 0x10, 0xc8, 0x64, 0x32, 0x7, 0xfb, 0x7,
    0x83, 0xc1, 0xe0, 0xbf, 0xc0,
    /* U+0043 "C" */
    0x7, 0x0, 0x18, 0x20, 0x0, 0xc0, 0xc0, 0xc0,
    0xc0, 0xc0, 0x3f,
    /* U+0044 "D" */
    0x3f, 0x10, 0x8, 0x24, 0x12, 0xe, 0x7, 0x3,
    0x81, 0xc3, 0x60, 0x3f, 0x0,
    /* U+0045 "E" */
    0x3f, 0x20, 0x20, 0xc0, 0xc0, 0xfc, 0xc0, 0xc0,
    0xc0, 0x0, 0x3f,
    /* U+0046 "F" */
    0x3f, 0x20, 0x20, 0xc0, 0xc0, 0xfc, 0xc0, 0xc0,
    0xc0, 0xc0, 0xc0,
    /* U+0047 "G" */
    0x7, 0xe0, 0x0, 0x60, 0x10, 0x0, 0x1, 0x8f,
    0xf0, 0x1e, 0x3, 0xc0, 0x80, 0x0, 0xfc, 0x0,
    /* U+0048 "H" */
    0x20, 0x90, 0x48, 0x38, 0x1c, 0xf, 0xff, 0xd,
    0x86, 0xc3, 0x61, 0xb0, 0xc0,
    /* U+0049 "I" */
    0x24, 0x93, 0xb6, 0xdb, 0x0,
    /* U+004A "J" */
    0x1f, 0x80, 0x40, 0x20, 0x10, 0x8, 0x4, 0xc,
    0x6, 0xc3, 0x0, 0xf, 0x0,
    /* U+004B "K" */
    0xc0, 0x60, 0x30, 0x38, 0x6c, 0x6, 0x60, 0xe0,
    0x70, 0x3c, 0x12, 0x8, 0xe0,
    /* U+004C "L" */
    0x20, 0x20, 0x20, 0xc0, 0xc0, 0xc0, 0xc0, 0xc0,
    0xc0, 0x0, 0x3f,
    /* U+004D "M" */
    0x21, 0xe7, 0x6c, 0x8d, 0x97, 0xb0, 0xc7, 0x98,
    0xf0, 0x1e, 0x3, 0xc0, 0x78, 0xf, 0x1, 0x80,
    /* U+004E "N" */
    0x0, 0x80, 0x0, 0x81, 0x9c, 0x32, 0x6, 0x58,
    0xcb, 0x19, 0x63, 0xc3, 0x78, 0xf, 0x3, 0x80,
    /* U+004F "O" */
    0x7, 0x80, 0x0, 0x61, 0x90, 0x3c, 0x7, 0x80,
    0xf0, 0x1e, 0x3, 0xc0, 0x80, 0x0, 0xfc, 0x0,
    /* U+0050 "P" */
    0x3f, 0x10, 0x48, 0x24, 0x12, 0x11, 0x3b, 0xe1,
    0x80, 0xc0, 0x60, 0x30, 0x0,
    /* U+0051 "Q" */
    0x7, 0x83, 0xc, 0x1, 0x90, 0x3c, 0x7, 0x80,
    0xf0, 0x1e, 0x0, 0xc0, 0x80, 0x0, 0xfc, 0x2,
    0x0, 0x40, 0x7, 0x0,
    /* U+0052 "R" */
    0x3f, 0x10, 0x48, 0x24, 0x12, 0x11, 0x1b, 0xf1,
    0x88, 0xc3, 0x60, 0x30, 0x20,
    /* U+0053 "S" */
    0x1f, 0x0, 0x20, 0xc0, 0x0, 0x3e, 0x1, 0x1,
    0x1, 0x0, 0xfe,
    /* U+0054 "T" */
    0xff, 0x82, 0x1, 0x0, 0x80, 0x40, 0xc0, 0x60,
    0x30, 0x18, 0xc, 0x6, 0x0,
    /* U+0055 "U" */
    0x20, 0x90, 0x48, 0x24, 0x1e, 0xe, 0x7, 0x3,
    0x81, 0xc1, 0x0, 0xf, 0x80,
    /* U+0056 "V" */
    0xc0, 0xe0, 0x70, 0x38, 0x6c, 0x36, 0x1b, 0x31,
    0x98, 0x2c, 0x10, 0xe, 0x0,
    /* U+0057 "W" */
    0x20, 0x64, 0xc, 0x81, 0xe0, 0x3c, 0xc7, 0x98,
    0xf7, 0x66, 0xc, 0xe3, 0x98, 0x33, 0x6, 0x0,
    /* U+0058 "X" */
    0xc0, 0xe0, 0x30, 0xc4, 0x81, 0x80, 0xc0, 0x70,
    0x0, 0x23, 0x0, 0x30, 0x20,
    /* U+0059 "Y" */
    0xc0, 0xe0, 0x70, 0x38, 0x6c, 0x31, 0x18, 0x70,
    0x18, 0xc, 0x6, 0x3, 0x0,
    /* U+005A "Z" */
    0xf8, 0x0, 0x0, 0x7c, 0xc, 0x3, 0x1, 0x1,
    0x81, 0x80, 0x60, 0x18, 0xf, 0xfc,
    /* U+0061 "a" */
    0x1c, 0x0, 0x23, 0xc3, 0xc3, 0xc7, 0xb, 0x3b,
    /* U+0062 "b" */
    0xc0, 0xc0, 0xc0, 0xf8, 0xc8, 0xcc, 0xc3, 0xc3,
    0xc3, 0x0, 0x3c,
    /* U+0063 "c" */
    0x1c, 0x0, 0x20, 0xc0, 0xc0, 0xc3, 0x0, 0x3c,
    /* U+0064 "d" */
    0x3, 0x3, 0x3, 0x1f, 0x23, 0x23, 0xc3, 0xc3,
    0xc7, 0x43, 0x3b,
    /* U+0065 "e" */
    0x38, 0xc, 0x7e, 0xc3, 0xc, 0xf,
    /* U+0066 "f" */
    0x18, 0x19, 0xf6, 0x31, 0x8c, 0x63, 0x18,
    /* U+0067 "g" */
    0x1c, 0x0, 0x23, 0xc3, 0x3, 0x3f, 0x3, 0x3,
    0x23, 0x0, 0x1c,
    /* U+0068 "h" */
    0x20, 0x20, 0x20, 0x20, 0x20, 0xfc, 0xc3, 0xc3,
    0xc3, 0xc3, 0xc3,
    /* U+0069 "i" */
    0xc3, 0xff, 0xc0,
    /* U+006A "j" */
    0x18, 0x0, 0x31, 0x8c, 0x63, 0x18, 0xc6, 0xe,
    0x0,
    /* U+006B "k" */
    0xc0, 0xc0, 0xc0, 0xc3, 0xc0, 0xcc, 0x38, 0x38,
    0x38, 0x20, 0x2c,
    /* U+006C "l" */
    0xff, 0xff, 0xfc,
    /* U+006D "m" */
    0xdf, 0x9d, 0x83, 0xb1, 0xe6, 0x3c, 0xc7, 0x98,
    0xf3, 0x1e, 0x63,
    /* U+006E "n" */
    0xfc, 0xc0, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3,
    /* U+006F "o" */
    0x3c, 0x0, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0x3c,
    /* U+0070 "p" */
    0xdc, 0xe3, 0xc3, 0xc3, 0xc0, 0xfc, 0xc0, 0xc0,
    0xc0, 0xc0, 0xc0,
    /* U+0071 "q" */
    0x1f, 0x23, 0x23, 0xc3, 0x43, 0x3f, 0x3, 0x3,
    0x3, 0x3, 0x3,
    /* U+0072 "r" */
    0xde, 0x39, 0x8c, 0x63, 0x18,
    /* U+0073 "s" */
    0x3c, 0xc, 0xe, 0x0, 0x10, 0x3e,
    /* U+0074 "t" */
    0x67, 0xd8, 0xc6, 0x31, 0x8c, 0x60,
    /* U+0075 "u" */
    0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0x0, 0x3c,
    /* U+0076 "v" */
    0xc3, 0xc3, 0xc3, 0xcc, 0xcc, 0x2c, 0x20, 0x38,
    /* U+0077 "w" */
    0xc0, 0xe6, 0x73, 0x39, 0x9d, 0xcf, 0x7b, 0xd,
    0x86,
    /* U+0078 "x" */
    0xc4, 0x0, 0x38, 0x38, 0x38, 0xc4, 0xc0, 0xc3,
    /* U+0079 "y" */
    0x23, 0xc3, 0xc3, 0xc3, 0x3, 0x3f, 0x3, 0x3,
    0x4, 0x0, 0x38,
    /* U+007A "z" */
    0xfc, 0x10, 0x46, 0x61, 0x86, 0x3f
};
/*---------------------
 *  GLYPH DESCRIPTION
 *--------------------*/
static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,
    {.bitmap_index = 0, .adv_w = 120, .box_w = 1, .box_h = 1, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1, .adv_w = 72, .box_w = 3, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 6, .adv_w = 96, .box_w = 5, .box_h = 3, .ofs_x = 0, .ofs_y = 10},
    {.bitmap_index = 8, .adv_w = 48, .box_w = 2, .box_h = 3, .ofs_x = 0, .ofs_y = 10},
    {.bitmap_index = 9, .adv_w = 96, .box_w = 6, .box_h = 16, .ofs_x = 0, .ofs_y = -3},
    {.bitmap_index = 21, .adv_w = 96, .box_w = 6, .box_h = 16, .ofs_x = 0, .ofs_y = -3},
    {.bitmap_index = 33, .adv_w = 144, .box_w = 8, .box_h = 7, .ofs_x = 0, .ofs_y = 4},
    {.bitmap_index = 40, .adv_w = 144, .box_w = 8, .box_h = 8, .ofs_x = 0, .ofs_y = 2},
    {.bitmap_index = 48, .adv_w = 72, .box_w = 3, .box_h = 4, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 50, .adv_w = 96, .box_w = 5, .box_h = 1, .ofs_x = 0, .ofs_y = 4},
    {.bitmap_index = 51, .adv_w = 48, .box_w = 2, .box_h = 1, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 52, .adv_w = 96, .box_w = 6, .box_h = 15, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 64, .adv_w = 168, .box_w = 8, .box_h = 11, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 75, .adv_w = 72, .box_w = 4, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 81, .adv_w = 144, .box_w = 8, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 92, .adv_w = 144, .box_w = 8, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 103, .adv_w = 144, .box_w = 8, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 114, .adv_w = 144, .box_w = 8, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 125, .adv_w = 144, .box_w = 8, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 136, .adv_w = 144, .box_w = 8, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 147, .adv_w = 144, .box_w = 8, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 158, .adv_w = 144, .box_w = 8, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 169, .adv_w = 48, .box_w = 2, .box_h = 5, .ofs_x = 0, .ofs_y = 2},
    {.bitmap_index = 171, .adv_w = 72, .box_w = 3, .box_h = 7, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 174, .adv_w = 120, .box_w = 6, .box_h = 4, .ofs_x = 0, .ofs_y = 4},
    {.bitmap_index = 177, .adv_w = 120, .box_w = 6, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 186, .adv_w = 168, .box_w = 9, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 199, .adv_w = 168, .box_w = 9, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 212, .adv_w = 144, .box_w = 8, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 223, .adv_w = 168, .box_w = 9, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 236, .adv_w = 144, .box_w = 8, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 247, .adv_w = 144, .box_w = 8, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 258, .adv_w = 192, .box_w = 11, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 274, .adv_w = 168, .box_w = 9, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 287, .adv_w = 72, .box_w = 3, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 292, .adv_w = 168, .box_w = 9, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 305, .adv_w = 168, .box_w = 9, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 318, .adv_w = 144, .box_w = 8, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 329, .adv_w = 192, .box_w = 11, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 345, .adv_w = 192, .box_w = 11, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 361, .adv_w = 192, .box_w = 11, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 377, .adv_w = 168, .box_w = 9, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 390, .adv_w = 192, .box_w = 11, .box_h = 14, .ofs_x = 0, .ofs_y = -3},
    {.bitmap_index = 410, .adv_w = 168, .box_w = 9, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 423, .adv_w = 144, .box_w = 8, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 434, .adv_w = 168, .box_w = 9, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 447, .adv_w = 168, .box_w = 9, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 460, .adv_w = 168, .box_w = 9, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 473, .adv_w = 192, .box_w = 11, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 489, .adv_w = 168, .box_w = 9, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 502, .adv_w = 168, .box_w = 9, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 515, .adv_w = 168, .box_w = 10, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 529, .adv_w = 144, .box_w = 8, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 537, .adv_w = 144, .box_w = 8, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 548, .adv_w = 144, .box_w = 8, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 556, .adv_w = 144, .box_w = 8, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 567, .adv_w = 120, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 573, .adv_w = 96, .box_w = 5, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 580, .adv_w = 144, .box_w = 8, .box_h = 11, .ofs_x = 0, .ofs_y = -3},
    {.bitmap_index = 591, .adv_w = 144, .box_w = 8, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 602, .adv_w = 48, .box_w = 2, .box_h = 9, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 605, .adv_w = 96, .box_w = 5, .box_h = 13, .ofs_x = 0, .ofs_y = -3},
    {.bitmap_index = 614, .adv_w = 144, .box_w = 8, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 625, .adv_w = 48, .box_w = 2, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 628, .adv_w = 192, .box_w = 11, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 639, .adv_w = 144, .box_w = 8, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 647, .adv_w = 144, .box_w = 8, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 655, .adv_w = 144, .box_w = 8, .box_h = 11, .ofs_x = 0, .ofs_y = -3},
    {.bitmap_index = 666, .adv_w = 144, .box_w = 8, .box_h = 11, .ofs_x = 0, .ofs_y = -3},
    {.bitmap_index = 677, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 682, .adv_w = 120, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 688, .adv_w = 96, .box_w = 5, .box_h = 9, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 694, .adv_w = 144, .box_w = 8, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 702, .adv_w = 144, .box_w = 8, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 710, .adv_w = 168, .box_w = 9, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 719, .adv_w = 144, .box_w = 8, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 727, .adv_w = 144, .box_w = 8, .box_h = 11, .ofs_x = 0, .ofs_y = -3},
    {.bitmap_index = 738, .adv_w = 120, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0}
};
/*---------------------
 *  CHARACTER MAPPING
 *--------------------*/
static const uint8_t glyph_id_ofs_list_0[] = {
    0, 1, 2, 0, 0, 0, 0, 3,
    4, 5, 6, 7, 8, 9, 10, 11,
    12, 13, 14, 15, 16, 17, 18, 19,
    20, 21, 22, 23, 0, 24, 0, 25
};
/*Collect the unicode lists and glyph_id offsets*/
static const lv_font_fmt_txt_cmap_t cmaps[] =
{
    {
        .range_start = 32, .range_length = 32, .glyph_id_start = 1,
        .unicode_list = NULL, .glyph_id_ofs_list = glyph_id_ofs_list_0, .list_length = 32, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_FULL
    },
    {
        .range_start = 65, .range_length = 26, .glyph_id_start = 27,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    },
    {
        .range_start = 97, .range_length = 26, .glyph_id_start = 53,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    }
};
/*--------------------
 *  ALL CUSTOM DATA
 *--------------------*/
/*Store all the custom data of the font*/
static lv_font_fmt_txt_glyph_cache_t cache;
static const lv_font_fmt_txt_dsc_t font_dsc = {
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 3,
    .bpp = 1,
    .kern_classes = 0,
    .bitmap_format = 0,
    .cache = &cache
};
/*-----------------
 *  PUBLIC FONT
 *----------------*/
/*Initialize a public general font descriptor*/
const lv_font_t comic_24 = {
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,    /*Function pointer to get glyph's data*/
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,    /*Function pointer to get glyph's bitmap*/
    .line_height = 16,          /*The maximum line height required by the font*/
    .base_line = 3,             /*Baseline measured from the bottom of the line*/

    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -1,
    .underline_thickness = 1,
    .dsc = &font_dsc,          /*The custom font data. Will be accessed by `get_glyph_bitmap/dsc` */
};

#endif 